version: 2

multi-ecosystem-groups:
  all-updates:
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "npm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
    groups:
      conventional-changelog:
        patterns:
          - "conventional-changelog*"
      github:
        patterns:
          - "@actions/core"
          - "@@octokit/rest"
      types:
        patterns:
          - "@types/*"
          - "@octokit/types"
      typedoc:
        patterns:
          - "typedoc*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
