name: "MS Teams Incoming Webhook Notification"
author: "mikesprague"
description: "GitHub Action to send an MS Teams notification via Incoming Webhook"

inputs:
  github-token:
    description: "GitHub Token"
    required: true
  webhook-url:
    description: "MS Teams Webhook URL"
    required: true
  title:
    description: "Message heading"
    required: true
  title-size:
    description: "Size of the title text ('Large' | 'Default')"
    required: false
    default: "Default"
  message:
    description: "Message to be sent"
    required: false
    default: ""
  color:
    description: "Notification header line color"
    required: false
    default: "default"
  deploy-card:
    description: "Send a GitHub deploy notification"
    required: false
    default: false
  show-commit-message:
    description: "Show the first line of the commit message in deploy-card notifications"
    required: false
    default: false
  timezone:
    description: "Timezone for message timestamps"
    required: false
    default: "America/New_York"
  user-mentions:
    description: "Teams user mentions in format 'name|id', comma separated (e.g. 'Alice|alice@example.com,Bob|bob@example.com', invalid entries are ignored). NOTE: id must be Entra ID or UPN/email of the user"
    required: false
    default: ""

runs:
  using: "node24"
  main: "dist/index.js"

branding:
  icon: "alert-octagon"
  color: "purple"
